# Generated by Django 5.2.15 on 2026-06-29 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Warteliste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text='Wir melden uns unter dieser Adresse, sobald ein Zugang frei wird.', max_length=254, verbose_name='E-Mail')),
                ('organisation_name', models.CharField(blank=True, help_text='Die Beringungs-Organisation, die du gründen möchtest (optional).', max_length=200, verbose_name='Organisation')),
                ('message', models.TextField(blank=True, help_text='Worum geht es? Erzähl uns kurz von deinem Vorhaben (optional).', verbose_name='Nachricht')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Angefragt am')),
            ],
            options={
                'verbose_name': 'Warteliste-Eintrag',
                'verbose_name_plural': 'Warteliste',
                'ordering': ['-created'],
            },
        ),
    ]
