# Generated by Django 5.2.15 on 2026-06-29 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='warteliste',
            name='approx_beringer_count',
            field=models.CharField(blank=True, help_text='Für wie viele Beringer sprichst du ungefähr? (optional)', max_length=50, verbose_name='Ungefähre Anzahl Beringer'),
        ),
        migrations.AddField(
            model_name='warteliste',
            name='contact_role',
            field=models.CharField(blank=True, help_text='Deine Funktion in der Organisation (z. B. wissenschaftliche Leitung) — nur für Organisations-Anfragen relevant.', max_length=200, verbose_name='Funktion / Rolle'),
        ),
        migrations.AddField(
            model_name='warteliste',
            name='lead_type',
            field=models.CharField(choices=[('beringer', 'Beringer (Warteliste)'), ('organisation', 'Organisation (Gespräch)')], default='beringer', help_text='Welcher Funnel den Lead hinterlassen hat.', max_length=20, verbose_name='Typ'),
        ),
    ]
