# Generated by Django 5.2.5 on 2025-08-19 13:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ring',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('number', models.CharField(max_length=64, unique=True)),
                ('size', models.CharField(choices=[('V', 'V'), ('T', 'T'), ('S', 'S'), ('X', 'X'), ('P', 'P')], default='V', max_length=3, verbose_name='Ringgröße')),
            ],
        ),
        migrations.CreateModel(
            name='Species',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('common_name_de', models.CharField(max_length=127, unique=True)),
                ('common_name_en', models.CharField(max_length=127, unique=True)),
                ('scientific_name', models.CharField(max_length=127, unique=True)),
                ('family_name', models.CharField(max_length=255)),
                ('order_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='DataEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ringing_station', models.CharField(default='ILLMITZ', max_length=124, verbose_name='Station')),
                ('net_location', models.PositiveIntegerField(verbose_name='Netznr.')),
                ('net_height', models.PositiveIntegerField(verbose_name='Netzfach')),
                ('net_direction', models.CharField(choices=[('L', 'Links'), ('R', 'Rechts')], default='L', max_length=1, verbose_name='Flugrichtung')),
                ('feather_span', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Federl. (mm)')),
                ('wing_span', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Flügell. (mm)')),
                ('tarsus', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Tarsus. (mm)')),
                ('notch_f2', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Kerbe F2 (mm)')),
                ('inner_foot', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Innenfuß (mm)')),
                ('weight_gram', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Gewicht (g)')),
                ('bird_status', models.CharField(choices=[('e', 'Erstfang'), ('w', 'Wiederfang')], default='e', max_length=1, verbose_name='Status')),
                ('fat_deposit', models.PositiveSmallIntegerField(null=True)),
                ('muscle_class', models.PositiveSmallIntegerField(choices=[(0, 'Null'), (1, 'One'), (2, 'Two'), (3, 'Three')], default=None, max_length=1, null=True, verbose_name='Muskelklasse')),
                ('age_class', models.CharField(choices=[(1, 'Nestling oder Nestflüchter'), (2, 'Fängling (Alter unbekannt)'), (3, 'Diesjährig'), (4, 'Nicht Diensjährig'), (5, 'Vorjährig'), (6, 'Nicht Vorjährig')], default=2, max_length=1, verbose_name='Alter')),
                ('sex', models.CharField(choices=[(0, 'Erstfang'), (1, 'Männlich'), (2, 'Weiblich')], default=0, max_length=1, verbose_name='Geschlecht')),
                ('small_feather_int', models.PositiveSmallIntegerField(choices=[(0, 'keine'), (1, 'bis zu 20 Federn'), (2, 'mehr als 20 Federn')], default=None, max_length=1, null=True, verbose_name='Kleingef. Int')),
                ('small_feather_app', models.PositiveSmallIntegerField(choices=[('J', 'Eben flügger Jungvogel'), ('U', 'Weniger als 1/3 erneuert'), ('M', 'Zwischen 1/3 und 2/2 erneuert'), ('N', 'Mehr als 2/3 erneuert')], default=None, max_length=1, null=True, verbose_name='Kleingef. Forts.')),
                ('hand_wing', models.PositiveSmallIntegerField(choices=[(0, 'Keine Handschwingen wachsen'), (1, 'Alle sind unvermausert'), (2, 'Mindestens eine mausert'), (3, 'Alle vermausert'), (4, 'Ein Teil ist vermausert')], default=None, max_length=1, null=True, verbose_name='Handschwinge')),
                ('date_time', models.DateTimeField(verbose_name='Datum')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('comment', models.CharField(max_length=2048, verbose_name='Bemerkungen')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Beringer')),
                ('ring', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='birds.ring', verbose_name='Ringnummer')),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='birds.species', verbose_name='Art')),
            ],
        ),
    ]
