# Generated by Django 5.2.5 on 2025-08-19 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birds', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataentry',
            name='hand_wing',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Keine Handschwingen wachsen'), (1, 'Alle sind unvermausert'), (2, 'Mindestens eine mausert'), (3, 'Alle vermausert'), (4, 'Ein Teil ist vermausert')], default=None, null=True, verbose_name='Handschwinge'),
        ),
        migrations.AlterField(
            model_name='dataentry',
            name='muscle_class',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Null'), (1, 'One'), (2, 'Two'), (3, 'Three')], default=None, null=True, verbose_name='Muskelklasse'),
        ),
        migrations.AlterField(
            model_name='dataentry',
            name='small_feather_app',
            field=models.PositiveSmallIntegerField(choices=[('J', 'Eben flügger Jungvogel'), ('U', 'Weniger als 1/3 erneuert'), ('M', 'Zwischen 1/3 und 2/2 erneuert'), ('N', 'Mehr als 2/3 erneuert')], default=None, null=True, verbose_name='Kleingef. Forts.'),
        ),
        migrations.AlterField(
            model_name='dataentry',
            name='small_feather_int',
            field=models.PositiveSmallIntegerField(choices=[(0, 'keine'), (1, 'bis zu 20 Federn'), (2, 'mehr als 20 Federn')], default=None, null=True, verbose_name='Kleingef. Int'),
        ),
    ]
