# Generated by Django 5.2.5 on 2025-08-20 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birds', '0003_import_species_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataentry',
            name='has_brood_patch',
            field=models.BooleanField(default=False, verbose_name='Brutfleck'),
        ),
        migrations.AddField(
            model_name='dataentry',
            name='has_cpl_plus',
            field=models.BooleanField(default=False, verbose_name='CPL+'),
        ),
        migrations.AddField(
            model_name='dataentry',
            name='has_hunger_stripes',
            field=models.BooleanField(default=False, verbose_name='Hungerstreifen'),
        ),
        migrations.AddField(
            model_name='dataentry',
            name='has_mites',
            field=models.BooleanField(default=False, verbose_name='Milben'),
        ),
    ]
