# Generated by Django 5.2.5 on 2025-08-20 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birds', '0004_dataentry_has_brood_patch_dataentry_has_cpl_plus_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataentry',
            name='age_class',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Nestling oder Nestflüchter'), (2, 'Fängling (Alter unbekannt)'), (3, 'Diesjährig'), (4, 'Nicht Diensjährig'), (5, 'Vorjährig'), (6, 'Nicht Vorjährig')], default=2, max_length=1, verbose_name='Alter'),
        ),
        migrations.AlterField(
            model_name='dataentry',
            name='sex',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Erstfang'), (1, 'Männlich'), (2, 'Weiblich')], default=0, max_length=1, verbose_name='Geschlecht'),
        ),
    ]
