# Generated by Django 5.2.5 on 2025-08-20 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birds', '0005_alter_dataentry_age_class_alter_dataentry_sex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataentry',
            name='small_feather_app',
            field=models.CharField(choices=[('J', 'Eben flügger Jungvogel'), ('U', 'Weniger als 1/3 erneuert'), ('M', 'Zwischen 1/3 und 2/2 erneuert'), ('N', 'Mehr als 2/3 erneuert')], default=None, null=True, verbose_name='Kleingef. Forts.'),
        ),
    ]
