# Generated by Django 5.2.5 on 2025-08-20 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birds', '0006_alter_dataentry_small_feather_app'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataentry',
            name='age_class',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Nestling oder Nestflüchter'), (2, 'Fängling (Alter unbekannt)'), (3, 'Diesjährig'), (4, 'Nicht Diensjährig'), (5, 'Vorjährig'), (6, 'Nicht Vorjährig')], default=2, verbose_name='Alter'),
        ),
        migrations.AlterField(
            model_name='dataentry',
            name='sex',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Erstfang'), (1, 'Männlich'), (2, 'Weiblich')], default=0, verbose_name='Geschlecht'),
        ),
        migrations.AlterField(
            model_name='dataentry',
            name='small_feather_app',
            field=models.CharField(choices=[('J', 'Eben flügger Jungvogel'), ('U', 'Weniger als 1/3 erneuert'), ('M', 'Zwischen 1/3 und 2/2 erneuert'), ('N', 'Mehr als 2/3 erneuert')], default=None, max_length=1, null=True, verbose_name='Kleingef. Forts.'),
        ),
    ]
