# Generated by Django 5.2.5 on 2025-08-21 07:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birds', '0007_alter_dataentry_age_class_alter_dataentry_sex_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RingingStation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('name', models.CharField(max_length=255)),
                ('handle', models.CharField(max_length=124, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='dataentry',
            name='comment',
            field=models.CharField(max_length=2048, null=True, verbose_name='Bemerkungen'),
        ),
        migrations.AlterField(
            model_name='dataentry',
            name='feather_span',
            field=models.DecimalField(decimal_places=2, max_digits=4, null=True, verbose_name='Federl. (mm)'),
        ),
        migrations.AlterField(
            model_name='dataentry',
            name='inner_foot',
            field=models.DecimalField(decimal_places=2, max_digits=4, null=True, verbose_name='Innenfuß (mm)'),
        ),
        migrations.AlterField(
            model_name='dataentry',
            name='net_direction',
            field=models.CharField(choices=[('L', 'Links'), ('R', 'Rechts')], default='L', max_length=1, null=True, verbose_name='Flugrichtung'),
        ),
        migrations.AlterField(
            model_name='dataentry',
            name='net_height',
            field=models.PositiveIntegerField(null=True, verbose_name='Netzfach'),
        ),
        migrations.AlterField(
            model_name='dataentry',
            name='net_location',
            field=models.PositiveIntegerField(null=True, verbose_name='Netznr.'),
        ),
        migrations.AlterField(
            model_name='dataentry',
            name='notch_f2',
            field=models.DecimalField(decimal_places=2, max_digits=4, null=True, verbose_name='Kerbe F2 (mm)'),
        ),
        migrations.AlterField(
            model_name='dataentry',
            name='tarsus',
            field=models.DecimalField(decimal_places=2, max_digits=4, null=True, verbose_name='Tarsus. (mm)'),
        ),
        migrations.AlterField(
            model_name='dataentry',
            name='weight_gram',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True, verbose_name='Gewicht (g)'),
        ),
        migrations.AlterField(
            model_name='dataentry',
            name='wing_span',
            field=models.DecimalField(decimal_places=2, max_digits=4, null=True, verbose_name='Flügell. (mm)'),
        ),
        migrations.CreateModel(
            name='Scientist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('handle', models.CharField(max_length=11, unique=True, verbose_name='Kürzel')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Beringer')),
            ],
        ),
        migrations.AlterField(
            model_name='dataentry',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='birds.scientist', verbose_name='Beringer'),
        ),
    ]
