# Generated by Django 5.2.5 on 2025-08-21 07:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birds', '0008_ringingstation_alter_dataentry_comment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataentry',
            name='ringing_station',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='birds.ringingstation', verbose_name='Station'),
        ),
    ]
