# Generated by Django 5.2.5 on 2025-08-21 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birds', '0009_alter_dataentry_ringing_station'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataentry',
            name='net_direction',
            field=models.CharField(choices=[('L', 'Links'), ('R', 'Rechts')], max_length=1, null=True, verbose_name='Flugrichtung'),
        ),
    ]
