# Generated by Django 5.2.5 on 2025-08-21 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birds', '0011_alter_dataentry_feather_span_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataentry',
            name='feather_span',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True, verbose_name='Federl. (mm)'),
        ),
        migrations.AlterField(
            model_name='dataentry',
            name='inner_foot',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True, verbose_name='Innenfuß (mm)'),
        ),
        migrations.AlterField(
            model_name='dataentry',
            name='notch_f2',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True, verbose_name='Kerbe F2 (mm)'),
        ),
        migrations.AlterField(
            model_name='dataentry',
            name='tarsus',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True, verbose_name='Tarsus. (mm)'),
        ),
        migrations.AlterField(
            model_name='dataentry',
            name='weight_gram',
            field=models.DecimalField(decimal_places=2, max_digits=7, null=True, verbose_name='Gewicht (g)'),
        ),
        migrations.AlterField(
            model_name='dataentry',
            name='wing_span',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True, verbose_name='Flügell. (mm)'),
        ),
    ]
