# Generated by Django 5.2.5 on 2025-08-21 10:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birds', '0012_alter_dataentry_feather_span_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataentry',
            name='comment',
            field=models.CharField(blank=True, max_length=2048, null=True, verbose_name='Bemerkungen'),
        ),
        migrations.AlterField(
            model_name='dataentry',
            name='fat_deposit',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dataentry',
            name='feather_span',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Federl. (mm)'),
        ),
        migrations.AlterField(
            model_name='dataentry',
            name='hand_wing',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Keine Handschwingen wachsen'), (1, 'Alle sind unvermausert'), (2, 'Mindestens eine mausert'), (3, 'Alle vermausert'), (4, 'Ein Teil ist vermausert')], default=None, null=True, verbose_name='Handschwinge'),
        ),
        migrations.AlterField(
            model_name='dataentry',
            name='inner_foot',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Innenfuß (mm)'),
        ),
        migrations.AlterField(
            model_name='dataentry',
            name='muscle_class',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Null'), (1, 'One'), (2, 'Two'), (3, 'Three')], default=None, null=True, verbose_name='Muskelklasse'),
        ),
        migrations.AlterField(
            model_name='dataentry',
            name='net_direction',
            field=models.CharField(blank=True, choices=[('L', 'Links'), ('R', 'Rechts')], max_length=1, null=True, verbose_name='Flugrichtung'),
        ),
        migrations.AlterField(
            model_name='dataentry',
            name='net_height',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Netzfach'),
        ),
        migrations.AlterField(
            model_name='dataentry',
            name='net_location',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Netznr.'),
        ),
        migrations.AlterField(
            model_name='dataentry',
            name='notch_f2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Kerbe F2 (mm)'),
        ),
        migrations.AlterField(
            model_name='dataentry',
            name='ringing_station',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='birds.ringingstation', verbose_name='Station'),
        ),
        migrations.AlterField(
            model_name='dataentry',
            name='small_feather_app',
            field=models.CharField(blank=True, choices=[('J', 'Eben flügger Jungvogel'), ('U', 'Weniger als 1/3 erneuert'), ('M', 'Zwischen 1/3 und 2/2 erneuert'), ('N', 'Mehr als 2/3 erneuert')], default=None, max_length=1, null=True, verbose_name='Kleingef. Forts.'),
        ),
        migrations.AlterField(
            model_name='dataentry',
            name='small_feather_int',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'keine'), (1, 'bis zu 20 Federn'), (2, 'mehr als 20 Federn')], default=None, null=True, verbose_name='Kleingef. Int'),
        ),
        migrations.AlterField(
            model_name='dataentry',
            name='tarsus',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Tarsus. (mm)'),
        ),
        migrations.AlterField(
            model_name='dataentry',
            name='weight_gram',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Gewicht (g)'),
        ),
        migrations.AlterField(
            model_name='dataentry',
            name='wing_span',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Flügell. (mm)'),
        ),
    ]
