# Generated by Django 5.2.5 on 2025-08-21 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birds', '0013_alter_dataentry_comment_alter_dataentry_fat_deposit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='species',
            name='ring_size',
            field=models.CharField(blank=True, choices=[('V', 'V'), ('T', 'T'), ('S', 'S'), ('X', 'X'), ('P', 'P')], max_length=3, null=True, verbose_name='Empfohlene Ringgröße'),
        ),
        migrations.AlterField(
            model_name='ring',
            name='number',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterUniqueTogether(
            name='ring',
            unique_together={('size', 'number')},
        ),
    ]
