# Generated by Django 5.2.5 on 2025-08-22 11:01

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birds', '0014_species_ring_size_alter_ring_number_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SpeciesList',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='List Name')),
                ('is_active', models.BooleanField(default=False, verbose_name='Active for Autocomplete')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('species', models.ManyToManyField(blank=True, related_name='lists', to='birds.species')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='species_lists', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'name')},
            },
        ),
    ]
