# Generated by Django 5.2.13 on 2026-04-26 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birds', '0019_dataentry_project_and_station_required'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataentry',
            name='muscle_class',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3')], default=None, null=True, verbose_name='Muskelklasse'),
        ),
        migrations.AlterField(
            model_name='dataentry',
            name='sex',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Unbestimmt'), (1, 'Männlich'), (2, 'Weiblich')], default=0, verbose_name='Geschlecht'),
        ),
    ]
