# Generated by Django 5.2.13 on 2026-04-26 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birds', '0020_alter_dataentry_muscle_class_alter_dataentry_sex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ring',
            name='size',
            field=models.CharField(choices=[('AS', 'AS'), ('BS', 'BS'), ('C', 'C'), ('D', 'D'), ('DS', 'DS'), ('DA', 'DA'), ('F', 'F'), ('FA', 'FA'), ('G', 'G'), ('GA', 'GA'), ('H', 'H'), ('HA', 'HA'), ('K', 'K'), ('KA', 'KA'), ('L', 'L'), ('LA', 'LA'), ('M', 'M'), ('N', 'N'), ('NA', 'NA'), ('P', 'P'), ('PA', 'PA'), ('R', 'R'), ('S', 'S'), ('SA', 'SA'), ('T', 'T'), ('TA', 'TA'), ('V', 'V'), ('X', 'X')], default='V', max_length=3, verbose_name='Ringgröße'),
        ),
        migrations.AlterField(
            model_name='species',
            name='ring_size',
            field=models.CharField(blank=True, choices=[('AS', 'AS'), ('BS', 'BS'), ('C', 'C'), ('D', 'D'), ('DS', 'DS'), ('DA', 'DA'), ('F', 'F'), ('FA', 'FA'), ('G', 'G'), ('GA', 'GA'), ('H', 'H'), ('HA', 'HA'), ('K', 'K'), ('KA', 'KA'), ('L', 'L'), ('LA', 'LA'), ('M', 'M'), ('N', 'N'), ('NA', 'NA'), ('P', 'P'), ('PA', 'PA'), ('R', 'R'), ('S', 'S'), ('SA', 'SA'), ('T', 'T'), ('TA', 'TA'), ('V', 'V'), ('X', 'X')], max_length=3, null=True, verbose_name='Empfohlene Ringgröße'),
        ),
    ]
