# Generated by Django 5.2.13 on 2026-04-30 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birds', '0023_repair_species_common_name_de_encoding'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='show_optional_fields',
            field=models.BooleanField(default=True, verbose_name='Optionale Felder anzeigen'),
        ),
    ]
