# Generated by Django 5.2.13 on 2026-06-13 20:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birds', '0025_fix_modern_taxonomy_ring_sizes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='scientist',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='Vorname'),
        ),
        migrations.AddField(
            model_name='scientist',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='Nachname'),
        ),
        migrations.AlterField(
            model_name='scientist',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Beringer'),
        ),
    ]
