# Generated by Django 5.2.13 on 2026-06-13 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birds', '0027_backfill_scientist_names'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scientist',
            name='handle',
            field=models.CharField(blank=True, max_length=11, unique=True, verbose_name='Kürzel'),
        ),
    ]
