# Generated by Django 5.2.13 on 2026-06-13 22:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birds', '0029_regenerate_handles_to_austrian_standard'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='default_station',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_for_projects', to='birds.ringingstation', verbose_name='Standard-Station'),
        ),
    ]
