# Generated by Django 5.2.15 on 2026-06-24 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birds', '0030_project_default_station'),
    ]

    operations = [
        migrations.AddField(
            model_name='species',
            name='is_sentinel',
            field=models.BooleanField(default=False, verbose_name='Spezial-Art (kein Vogel)'),
        ),
        migrations.AlterField(
            model_name='dataentry',
            name='age_class',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Nestling oder Nestflüchter'), (2, 'Fängling (Alter unbekannt)'), (3, 'Diesjährig'), (4, 'Nicht Diensjährig'), (5, 'Vorjährig'), (6, 'Nicht Vorjährig')], default=2, null=True, verbose_name='Alter'),
        ),
        migrations.AlterField(
            model_name='dataentry',
            name='bird_status',
            field=models.CharField(blank=True, choices=[('e', 'Erstfang'), ('w', 'Wiederfang')], default='e', max_length=1, null=True, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='dataentry',
            name='sex',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Unbestimmt'), (1, 'Männlich'), (2, 'Weiblich')], default=0, null=True, verbose_name='Geschlecht'),
        ),
    ]
