# Generated by Django 5.2.15 on 2026-06-24 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birds', '0032_create_ring_vernichtet_sentinel'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='capture_method',
            field=models.CharField(choices=[('Z', 'unbekannt'), ('H', 'mit der Hand gefangen'), ('N', 'am Nest, alle Methoden außer Handfang'), ('M', 'Japannetz'), ('W', 'Käfigfalle (Reuse)'), ('L', 'Klappnetz'), ('U', 'Hollandfalle'), ('O', 'mit sonstigem Netz'), ('T', 'Helgolandreuse oder Entenlocke'), ('S', 'Ball-Chatri oder Schlingen-Falle'), ('D', 'mit Blend-Licht'), ('A', 'durch Beringer ausgelöste Falle'), ('B', 'durch Vogel selbst ausgelöste Falle')], default='M', max_length=1, verbose_name='Fangmethode'),
        ),
        migrations.AddField(
            model_name='project',
            name='circumstance',
            field=models.CharField(default='25', max_length=8, verbose_name='Umstand'),
        ),
        migrations.AddField(
            model_name='project',
            name='lure',
            field=models.CharField(choices=[('U', 'unbekannt'), ('N', 'sicher kein Lockmittel'), ('M', 'mehr als ein Lockmittel'), ('A', 'Futter als Lockmittel'), ('B', 'Wasser als Lockmittel'), ('C', 'Licht als Lockmittel'), ('D', 'lebender Lockvogel'), ('E', 'künstlicher/ausgestopfter Lockvogel'), ('F', 'Klangattrappe (gleiche Art)'), ('G', 'Klangattrappe (andere Arten)'), ('H', 'Lockpfeife')], default='N', max_length=1, verbose_name='Lockmittel'),
        ),
        migrations.AddField(
            model_name='ringingstation',
            name='country',
            field=models.CharField(blank=True, max_length=64, verbose_name='Land'),
        ),
        migrations.AddField(
            model_name='ringingstation',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Breitengrad'),
        ),
        migrations.AddField(
            model_name='ringingstation',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Längengrad'),
        ),
        migrations.AddField(
            model_name='ringingstation',
            name='place_code',
            field=models.CharField(blank=True, max_length=16, verbose_name='Ortskodierung'),
        ),
        migrations.AddField(
            model_name='ringingstation',
            name='region',
            field=models.CharField(blank=True, max_length=128, verbose_name='Region'),
        ),
    ]
