# Generated by Django 5.2.15 on 2026-06-29 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birds', '0034_seed_iwm_station_and_project_context'),
    ]

    operations = [
        migrations.AddField(
            model_name='species',
            name='special_kind',
            field=models.CharField(blank=True, choices=[('', 'Normale Art'), ('ring_destroyed', 'Ring vernichtet'), ('unknown_species', 'Unbekannte Art (Aves ignota)')], default='', max_length=32, verbose_name='Sonderart'),
        ),
    ]
