# Generated by Django 5.2.15 on 2026-06-29 10:18

import birds.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birds', '0034_seed_iwm_station_and_project_context'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataentry',
            name='staff',
            field=models.ForeignKey(on_delete=models.SET(birds.models.get_fallback_beringer), to='birds.scientist', verbose_name='Beringer'),
        ),
    ]
