# Generated by Django 5.2.15 on 2026-06-29 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('birds', '0037_create_aves_ignota'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='species',
            name='is_sentinel',
        ),
    ]
