# Generated by Django 5.2.15 on 2026-06-29 17:41

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birds', '0040_remove_species_is_sentinel'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mitgliedschaft',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rolle', models.CharField(choices=[('admin', 'Admin'), ('mitglied', 'Mitglied')], default='mitglied', max_length=16, verbose_name='Rolle')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mitgliedschaften', to='birds.organization', verbose_name='Organisation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mitgliedschaften', to=settings.AUTH_USER_MODEL, verbose_name='Konto')),
            ],
            options={
                'verbose_name': 'Mitgliedschaft',
                'verbose_name_plural': 'Mitgliedschaften',
                'unique_together': {('user', 'organization')},
            },
        ),
    ]
