# Generated by Django 5.2.15 on 2026-06-29 17:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birds', '0041_mitgliedschaft'),
    ]

    operations = [
        migrations.AddField(
            model_name='scientist',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='scientists', to='birds.organization', verbose_name='Organisation'),
        ),
    ]
