# Generated by Django 5.2.15 on 2026-06-29 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birds', '0042_scientist_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='beta_cohort',
            field=models.BooleanField(default=False, verbose_name='Beta-Kohorte'),
        ),
        migrations.AddField(
            model_name='organization',
            name='plan',
            field=models.CharField(choices=[('beta', 'Beta')], default='beta', max_length=16, verbose_name='Plan'),
        ),
        migrations.AddField(
            model_name='organization',
            name='seat_limit',
            field=models.PositiveIntegerField(default=5, verbose_name='Seat-Limit'),
        ),
    ]
