# Generated by Django 5.2.15 on 2026-06-29 17:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birds', '0043_organization_beta_cohort_organization_plan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataentry',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='data_entries', to='birds.organization', verbose_name='Organisation'),
        ),
    ]
