# Generated by Django 5.2.15 on 2026-06-29 18:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birds', '0045_backfill_dataentry_organization'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ring',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='ring',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rings', to='birds.organization', verbose_name='Organisation'),
        ),
        migrations.AlterUniqueTogether(
            name='ring',
            unique_together={('organization', 'size', 'number')},
        ),
    ]
