# Generated by Django 5.2.15 on 2026-06-29 19:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birds', '0047_backfill_ring_organization'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zugangscode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=64, unique=True, verbose_name='Zugangscode')),
                ('note', models.CharField(blank=True, help_text='Optionaler Vermerk des Betreibers (für wen / warum ausgestellt).', max_length=255, verbose_name='Notiz')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('used_at', models.DateTimeField(blank=True, null=True, verbose_name='Eingelöst am')),
                ('founded_organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='founding_codes', to='birds.organization', verbose_name='Gegründete Organisation')),
            ],
            options={
                'verbose_name': 'Zugangscode',
                'verbose_name_plural': 'Zugangscodes',
            },
        ),
    ]
