# Generated by Django 5.2.15 on 2026-06-29 20:23

import birds.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birds', '0048_zugangscode'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrgEinladung',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, verbose_name='E-Mail')),
                ('rolle', models.CharField(choices=[('admin', 'Admin'), ('mitglied', 'Mitglied')], default='mitglied', max_length=16, verbose_name='Rolle')),
                ('token', models.CharField(default=birds.models.generate_invite_token, editable=False, max_length=64, unique=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True, verbose_name='Angenommen am')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('invited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_invitations', to=settings.AUTH_USER_MODEL, verbose_name='Eingeladen von')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='birds.organization', verbose_name='Organisation')),
            ],
            options={
                'verbose_name': 'Org-Einladung',
                'verbose_name_plural': 'Org-Einladungen',
                'ordering': ('-created',),
            },
        ),
    ]
