# Generated by Django 5.2.15 on 2026-06-30 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birds', '0050_cutover_to_iwm_linz'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='agb_accepted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='AGB/DPA akzeptiert am'),
        ),
    ]
