# Generated by Django 5.2.15 on 2026-07-01 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birds', '0051_organization_agb_accepted_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='ringingstation',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Aktiv'),
        ),
    ]
