# Generated by Django 5.2.15 on 2026-07-02 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birds', '0052_ringingstation_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataentry',
            name='idempotency_key',
            field=models.UUIDField(blank=True, null=True, verbose_name='Idempotenzschlüssel'),
        ),
        migrations.AddConstraint(
            model_name='dataentry',
            constraint=models.UniqueConstraint(fields=('organization', 'idempotency_key'), name='unique_idempotency_key_per_organization'),
        ),
    ]
