# Generated by Django 5.2.15 on 2026-07-02 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birds', '0053_dataentry_idempotency_key'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='dataentry',
            constraint=models.UniqueConstraint(condition=models.Q(('bird_status', 'e')), fields=('ring',), name='unique_erstfang_per_ring'),
        ),
    ]
