# Generated by Django 5.2.15 on 2026-07-03 10:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birds', '0054_dataentry_unique_erstfang_per_ring'),
    ]

    operations = [
        migrations.CreateModel(
            name='Central',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scheme_code', models.CharField(max_length=8, unique=True, verbose_name='Zentralen-Code')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('country', models.CharField(blank=True, max_length=64, verbose_name='Land')),
            ],
            options={
                'verbose_name': 'Zentrale',
                'verbose_name_plural': 'Zentralen',
                'ordering': ('scheme_code',),
            },
        ),
        migrations.AlterUniqueTogether(
            name='ring',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='project',
            name='central',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='birds.central', verbose_name='Zentrale'),
        ),
        migrations.AddField(
            model_name='ring',
            name='central',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rings', to='birds.central', verbose_name='Zentrale'),
        ),
        migrations.AlterUniqueTogether(
            name='ring',
            unique_together={('organization', 'central', 'size', 'number')},
        ),
    ]
