# Generated by Django 5.2.15 on 2026-07-03 14:17

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birds', '0058_widen_ring_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpeciesNorm',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('weight_mean', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True, verbose_name='Gewicht Ø (g)')),
                ('weight_sd', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True, verbose_name='Gewicht SD (g)')),
                ('feather_mean', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True, verbose_name='Federl. Ø (mm)')),
                ('feather_sd', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True, verbose_name='Federl. SD (mm)')),
                ('wing_mean', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True, verbose_name='Flügell. Ø (mm)')),
                ('wing_sd', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True, verbose_name='Flügell. SD (mm)')),
                ('tarsus_mean', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True, verbose_name='Tarsus Ø (mm)')),
                ('tarsus_sd', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True, verbose_name='Tarsus SD (mm)')),
                ('notch_f2_mean', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True, verbose_name='Kerbe F2 Ø (mm)')),
                ('notch_f2_sd', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True, verbose_name='Kerbe F2 SD (mm)')),
                ('inner_foot_mean', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True, verbose_name='Innenfuß Ø (mm)')),
                ('inner_foot_sd', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True, verbose_name='Innenfuß SD (mm)')),
                ('quotient_mean', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True, verbose_name='Quotient Ø')),
                ('quotient_tolerance_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Quotient Toleranz %')),
                ('sd_factor', models.DecimalField(blank=True, decimal_places=3, default=Decimal('1.96'), max_digits=5, null=True, verbose_name='SD-Faktor')),
                ('geschlechtsbestimmung_moeglich', models.BooleanField(blank=True, null=True, verbose_name='Geschlechtsbestimmung möglich')),
                ('dj_grossgefiedermauser_moeglich', models.BooleanField(blank=True, null=True, verbose_name='bei dj. Großgefiedermauser möglich')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='species_norms', to='birds.organization', verbose_name='Organisation')),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='norms', to='birds.species', verbose_name='Art')),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('organization__isnull', True)), fields=('species',), name='unique_global_default_species_norm'), models.UniqueConstraint(fields=('species', 'organization'), name='unique_species_norm_per_org')],
            },
        ),
    ]
