# Generated by Django 5.2.15 on 2026-07-04 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birds', '0061_seed_species_norms'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='projekttyp',
            field=models.CharField(choices=[('IWM', 'IWM'), ('IMS', 'IMS'), ('ZUGVOGELMONITORING', 'Zugvogelmonitoring'), ('NESTLINGSBERINGUNG', 'Nestlingsberingung'), ('SONSTIGES', 'Sonstiges')], default='SONSTIGES', max_length=32, verbose_name='Projekttyp'),
        ),
    ]
