# Generated by Django 5.2.15 on 2026-07-04 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birds', '0062_project_projekttyp'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='show_net_fields',
            field=models.BooleanField(default=True, verbose_name='Netzfelder anzeigen'),
        ),
    ]
