# Generated by Django 5.2.15 on 2026-07-16 06:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birds', '0063_project_show_net_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='saison_end_month',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)], verbose_name='Saison-Endmonat'),
        ),
        migrations.AddField(
            model_name='project',
            name='saison_start_month',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)], verbose_name='Saison-Startmonat'),
        ),
    ]
