# Generated by Django 5.2.15 on 2026-07-16 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birds', '0063_project_show_net_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataentry',
            name='is_dead_recovery',
            field=models.BooleanField(default=False, verbose_name='Tot-Fund'),
        ),
        migrations.AddField(
            model_name='dataentry',
            name='is_non_standard',
            field=models.BooleanField(default=False, verbose_name='Nicht-Standard-Fang'),
        ),
    ]
