# Generated by Django 5.2.15 on 2026-07-16 06:03

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birds', '0063_project_show_net_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpeciesRingSizeOverride',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ring_size', models.CharField(choices=[('AS', 'AS'), ('BS', 'BS'), ('C', 'C'), ('D', 'D'), ('DS', 'DS'), ('DA', 'DA'), ('F', 'F'), ('FA', 'FA'), ('G', 'G'), ('GA', 'GA'), ('H', 'H'), ('HA', 'HA'), ('K', 'K'), ('KA', 'KA'), ('L', 'L'), ('LA', 'LA'), ('M', 'M'), ('N', 'N'), ('NA', 'NA'), ('P', 'P'), ('PA', 'PA'), ('R', 'R'), ('S', 'S'), ('SA', 'SA'), ('T', 'T'), ('TA', 'TA'), ('V', 'V'), ('X', 'X')], max_length=3, verbose_name='Empfohlene Ringgröße')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='species_ring_size_overrides', to='birds.organization', verbose_name='Organisation')),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ring_size_overrides', to='birds.species', verbose_name='Art')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('species', 'organization'), name='unique_ring_size_override_per_org')],
            },
        ),
    ]
