# Generated by Django 5.2.15 on 2026-07-16 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('birds', '0064_dataentry_is_dead_recovery_dataentry_is_non_standard'),
        ('birds', '0064_project_saison_end_month_project_saison_start_month'),
        ('birds', '0064_speciesringsizeoverride'),
    ]

    operations = [
    ]
