# Generated by Django 5.2.15 on 2026-07-16 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('birds', '0065_merge_20260716'),
        ('birds', '0065_merge_20260716_0926'),
    ]

    operations = [
    ]
