# Generated by Django 5.2.15 on 2026-07-16 07:53

from django.db import migrations, models


def has_mites_to_parasites(apps, schema_editor):
    """Carry historical Milben captures onto the multi-valued Parasit field
    (ADR 0027): every ``has_mites=True`` row becomes ``parasites == ["mites"]``,
    so a Milben entry keeps its meaning as Parasit = Milben. Rows with
    ``has_mites=False`` keep the field's default empty list."""
    DataEntry = apps.get_model("birds", "DataEntry")
    DataEntry.objects.filter(has_mites=True).update(parasites=["mites"])


def parasites_to_has_mites(apps, schema_editor):
    """Reverse: fold a Parasit selection back onto the has_mites boolean. A
    capture whose parasites include ``"mites"`` reads as ``has_mites=True`` again;
    any other parasite type has no boolean to land on and is dropped."""
    DataEntry = apps.get_model("birds", "DataEntry")
    for entry in DataEntry.objects.all():
        entry.has_mites = "mites" in (entry.parasites or [])
        entry.save(update_fields=["has_mites"])


class Migration(migrations.Migration):

    dependencies = [
        ('birds', '0066_merge_0065_merge_20260716_0065_merge_20260716_0926'),
    ]

    operations = [
        # Add the new multi-valued field first so the data migration can copy the
        # boolean onto it before the old column is dropped.
        migrations.AddField(
            model_name='dataentry',
            name='parasites',
            field=models.JSONField(blank=True, default=list, verbose_name='Parasit'),
        ),
        migrations.RunPython(has_mites_to_parasites, parasites_to_has_mites),
        migrations.RemoveField(
            model_name='dataentry',
            name='has_mites',
        ),
    ]
