# Generated by Django 5.2.15 on 2026-07-16 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birds', '0067_remove_dataentry_has_mites_dataentry_parasites'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataentry',
            name='is_cancelled',
            field=models.BooleanField(default=False, verbose_name='Gelöscht'),
        ),
    ]
