# Generated by Django 5.2.15 on 2026-07-16 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birds', '0068_dataentry_is_cancelled'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='dataentry',
            name='unique_erstfang_per_ring',
        ),
        migrations.AddConstraint(
            model_name='dataentry',
            constraint=models.UniqueConstraint(condition=models.Q(('bird_status', 'e'), ('is_cancelled', False)), fields=('ring',), name='unique_erstfang_per_ring'),
        ),
    ]
