# Generated by Django 5.2.15 on 2026-07-16 19:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birds', '0070_parasit_mites_to_red_mites'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UnmigratablePayload',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('payload', models.JSONField(verbose_name='Payload')),
                ('schema_version', models.IntegerField(blank=True, null=True, verbose_name='Payload-Schema-Version')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unmigratable_payloads', to=settings.AUTH_USER_MODEL, verbose_name='Eingereicht von')),
            ],
            options={
                'verbose_name': 'Nicht migrierbarer Payload',
                'verbose_name_plural': 'Nicht migrierbare Payloads',
                'ordering': ['-created'],
            },
        ),
    ]
